version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "monthly" 
    commit-message:
      prefix: "deps(gomod)" 
  
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly" 
    commit-message:
      prefix: "deps(npm)"
    open-pull-requests-limit: 5
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" 