# GET  http://localhost:8080/handler HTTP/1.1
# content-type: application/json


# POST http://localhost:8080/api/v1/users HTTP/1.1
# content-type: application/json

# {
#     "name" : "",
#     "email": "",
#     "occupation": "",
#     "password": "password"
# }

# POST http://localhost:8080/api/v1/sessions HTTP/1.1
# content-type: application/json

# {
#     "email": "zaky@gmail.com",
#     "password": "password"
# }

# POST http://localhost:8080/api/v1/email_checkers HTTP/1.1
# content-type: application/json

# {
#     "email": "zaky@gmail.com"
# }

