version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=localhost
      - DB_USER=postgres
      - DB_PASSWORD=
      - DB_NAME=
      - DB_PORT=
      - DB_SSLMODE=disable
      - DB_TIMEZONE=
      - MIDTRANS_SERVER_KEY=
      - MIDTRANS_CLIENT_KEY=
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - "3306:3306"
    volumes:
      - ./database/postgress.sql:/docker-entrypoint-initdb.d
